### ISSUE TITLE
Conformance tests: Align automated and manual scoring

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing#1692]
In #1678 I added an automated tool for scoring the conformance test suite, and #1682 and #1683 added some features to support edge cases.

Now I am working on going through the remaining files where the automated conformance judgment on a file differs from the manual one (open PRs: #1684, #1685, #1687, #1688, #1689, #1690, #1691).

I'll use this issue to track the remaining discrepancies (from `conformance/src/unexpected_fails.py`):

- [x] mypy/dataclasses_usage.toml: Pass vs. Fail (#1684)
- [x] mypy/directives_version_platform.toml: Pass vs. Fail (#1685)
- [ ] mypy/namedtuples_define_functional.toml: Pass vs. Fail
- [x] mypy/overloads_basic.toml: Pass vs. Fail (#1687)
- [x] mypy/specialtypes_never.toml: Pass vs. Fail (#1688)
- [x] mypy/typeddicts_alt_syntax.toml: Pass vs. Fail (#1689)
- [x] mypy/typeddicts_type_consistency.toml: Pass vs. Fail (#1690)
- [ ] pyre/directives_reveal_type.toml: Unsupported vs. Pass
- [ ] pyre/namedtuples_define_functional.toml: Pass vs. Fail
- [x] pyright/classes_override.toml: Pass vs. Fail (#1691)
- [ ] pyright/dataclasses_frozen.toml: Pass vs. Fail
- [ ] pyright/dataclasses_slots.toml: Pass vs. Fail
- [ ] pyright/dataclasses_transform_field.toml: Pass vs. Fail
- [ ] pyright/dataclasses_transform_func.toml: Pass vs. Fail
- [ ] pyright/generics_defaults.toml: Pass vs. Fail
- [ ] pyright/literals_literalstring.toml: Pass vs. Fail
- [x] pyright/overloads_basic.toml: Pass vs. Fail (#1687)
- [ ] pyright/protocols_variance.toml: Pass vs. Fail
- [x] pyright/specialtypes_never.toml: Pass vs. Fail (#1688)
- [ ] pyright/tuples_unpacked.toml: Pass vs. Fail
- [x] pytype/dataclasses_usage.toml: Pass vs. Fail (#1684)
- [ ] pytype/directives_assert_type.toml: Pass vs. Fail
- [x] pytype/directives_version_platform.toml: Pass vs. Fail (#1685)
- [ ] pytype/generics_scoping.toml: Pass vs. Fail
- [ ] pytype/typeddicts_inheritance.toml: Pass vs. Fail

Any help is appreciated.

**Comment by JelleZijlstra** [comment]
The only remaining issue now is `mypy/namedtuples_define_functional.toml`. There the next mypy release should have full support (python/mypy#17247), which will remove the discrepancy.
